test:
	echo 'Inside prod';
	echo ${PORT}



open-keeper-dev:
	echo 'Running open-keeper'; \
	cd app; \
	python3 -u keeper.py --bot open;

close-keeper-dev:
	echo 'Running close-keeper'; \
	cd app; \
	python3 -u keeper.py --bot close;

